### ISSUE TITLE
Turn Auto-Numbering Off For Specific Files

### ISSUE THREAD

**Issue by jagrme00** [onlyafly/number-headings-obsidian#43]
The auto numbering option (that is enabled through the settings) triggers auto numbering of any file which is opened in the editor. Is there a possibility to turn this feature off for specific files? Adding a "manual" or "off" option to the front matter would solve the problem.

For me it interferes with the [Kanban Plugin](https://github.com/mgmeyers/obsidian-kanban) when I want to archive cards.

**Comment by onlyafly** [comment]
Interesting idea. I'll look into it

**Comment by jayambede** [comment]
Small addition ... might this also be achieved with a css-class? That would n't need another property in the list ... if that's an option ...

**Comment by onlyafly** [comment]
Fixed in the next version. Coming out later today. You can use "number headings: off" in the front matter to disable numbering.

**Comment by xiaoJonny** [comment]
![1711426547690](https://github.com/onlyafly/number-headings-obsidian/assets/106260555/91503989-3b6f-4d36-9025-f12807f5665f)
Hello! I added "number headings: off" to the frontmatte as you did, but the automatic numbering of this document still cannot be turned off (a screenshot is attached). Can you tell me what to do?

**Comment by homecls** [comment]
> Fixed in the next version. Coming out later today. You can use "number headings: off" in the front matter to disable numbering.

not work for me
